name: Clean

on: [workflow_dispatch]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Website Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          ports: ${{ secrets.PORT }}
          script: |
            unalias rm
            rm -rf cmsc389T-web-template
